apps/reserva/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', reserva_view, name='reserva'),
    path('agregar/', agrega_reserva_view, name='agrega_reserva'),
    path('editar/<int:id>/', edita_reserva_view, name='edita_reserva'),
    path('cancelar/', cancela_reserva_view, name='cancela_reserva'),
    path('buscar_disponibilidad/', busca_disponibilidad_view, name='busca_disponibilidad'),

    path('genera_numero_reserva/', numero_reserva, name="genera_numero_reserva"),
    path('reservar/', reserva_motor, name="reservar"),
    path('confirmar/', confirma_motor, name="confirmar"),
]

motorreserva/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


handler404 = 'apps.configuracion.views.error_404'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),

    path('dashboard/', include('apps.dashboard.urls')),
    path('configura/', include('apps.configuracion.urls')),
    path('edificio/', include('apps.edificio.urls')),
    path('habitacion/', include('apps.habitacion.urls')),
    path('tarifa/', include('apps.tarifa.urls')),
    path('reserva/', include('apps.reserva.urls')),
    path('sitio/', include('apps.sitio.urls')),
    path('motor/', include('apps.motor.urls')),
    path('perfil/', include('apps.perfil.urls')),
    path('reporte/', include('apps.reporte.urls')),
    path('digital/', include('apps.digital.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reserva/models.py
from django.db import models
from apps.habitacion.models import Habitacion
from apps.edificio.models import Edificio


class Reserva(models.Model):
	TIPO_CAMBIO = (
		(0, 'Dólares'),
		(1, 'Euros'),
		(2, 'Pesos Mexicanos'),
	)

	fecha_reservacion = models.DateField(default='') # fharesda
	numero_reservacion = models.CharField(max_length=8, blank=True, null=True) # numresda
	hora_reservacion = models.CharField(max_length=8, default='') # horaresda
	fecha_entrada = models.DateField() # fhaentda
	fecha_salida = models.DateField() # fhasalda
	tipo_habitacion = models.ForeignKey(Habitacion, on_delete=models.CASCADE) # cveestda1
	cuartos = models.IntegerField() # numcuada
	adultos = models.IntegerField() # numperda
	ninos = models.IntegerField() # numninda
	segmento_mercado = models.CharField(max_length=5, blank=True, null=True)  # cveestda4
	agencia = models.CharField(max_length=5, blank=True, null=True) # cveestda2
	nombre = models.CharField(max_length=100, default='') # nombr_da
	apellido_paterno = models.CharField(max_length=100, default='') # appat_da
	apellido_materno = models.CharField(max_length=100, blank=True, null=True) # apmat_da
	correo = models.CharField(max_length=200, default='') # email_da
	telefono = models.CharField(max_length=18, default='') # telefoda
	ciudad = models.CharField(max_length=80, default='', blank=True, null=True) # ciudadda
	estado = models.CharField(max_length=80, default='', blank=True, null=True) # estadoda
	pais = models.CharField(max_length=50, default='', blank=True, null=True) # paisda
	codigo_postal = models.CharField(max_length=10, default='', blank=True, null=True) # codposda
	deposito = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True) # deposida
	fecha_deposito = models.DateField(blank=True, null=True) # fhadepda
	moneda = models.IntegerField(choices=TIPO_CAMBIO, blank=True, null=True) # tpocam1da
	tarifa = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True) # tarifada
	comentario = models.TextField(default='', blank=True, null=True) # observda
	usuario_reserva = models.CharField(max_length=4, default='WEB', blank=True, null=True) # iniresda
	status = models.CharField(max_length=1, default='R', blank=True, null=True) # statusda
	registro_creado = models.DateTimeField(auto_now_add=True)
	registro_actualizado = models.DateTimeField(auto_now=True)
	hotel = models.ForeignKey(Edificio, on_delete=models.CASCADE, blank=True, null=True)

	class Meta:
		verbose_name = 'Reserva'
		verbose_name_plural = 'Reservaciones'

	def __str__(self):
		return '%s %s %s' % (self.nombre, self.apellido_paterno, self.apellido_materno)

apps/reserva/forms.py
from django import forms
from .models import Reserva


class ReservaForm(forms.ModelForm):
	class Meta:
		model = Reserva
		fields = '__all__'
		widgets = {
			'fecha_reservacion': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'hidden': 'hidden'}),
			'numero_reservacion': forms.TextInput(attrs={'class': 'form-control numero_reserva', 'readonly': 'readonly'}),
			'hora_reservacion': forms.TextInput(attrs={'class': 'form-control', 'hidden': 'hidden'}),
			'fecha_entrada': forms.TextInput(attrs={'class': 'form-control fecha', 'type': 'date'}),
			'fecha_salida': forms.TextInput(attrs={'class': 'form-control fecha', 'type': 'date'}),
			'tipo_habitacion': forms.Select(attrs={'class': 'form-select cincuenta'}),
			'cuartos': forms.TextInput(attrs={'class': 'form-control cincuenta'}),
			'adultos': forms.TextInput(attrs={'class': 'form-control'}),
			'ninos': forms.TextInput(attrs={'class': 'form-control'}),
			'segmento_mercado': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
			'agencia': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
			'nombre': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Nombre'}),
			'apellido_paterno': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Apellido Paterno'}),
			'apellido_materno': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Apellido Materno'}),
			'correo': forms.TextInput(attrs={'class': 'form-control treinta'}),
			'telefono': forms.TextInput(attrs={'class': 'form-control treinta'}),
			'ciudad': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'Ciudad'}),
			'estado': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'Estado'}),
			'pais': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'País'}),
			'codigo_postal': forms.TextInput(attrs={'class': 'form-control treinta'}),
			'deposito': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'value': '0.00'}),
			'fecha_deposito': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
			'moneda': forms.Select(attrs={'class': 'form-select'}),
			'tarifa': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'value': '0.00'}),
			'comentario': forms.Textarea(attrs={'class': 'form-control'}),
			'usuario_reserva': forms.TextInput(attrs={'class': 'form-control', 'value': 'WEB', 'hidden': 'hidden'}),
			'status': forms.TextInput(attrs={'class': 'form-control', 'value': 'R', 'hidden': 'hidden'}),
			'hotel': forms.NumberInput(attrs={'class': 'form-control'}),
		}

apps/reserva/views.py
#import json
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Reserva
from .forms import ReservaForm
from apps.habitacion.models import Habitacion
from apps.configuracion.models import DbDatos
from apps.configuracion.forms import DbDatosForm
from apps.configuracion.models import TabEst, TabHt
from apps.motor.views import trae_datos
from apps.edificio.models import Edificio


@login_required
def reserva_view(request):
	hotel = Edificio.objects.all().values('nombre_corto')
	if request.method == 'GET':
		opcion = request.GET.get('opcion')
		if opcion:
			consulta = list(Reserva.objects.filter(status=opcion).order_by('-id').values('id', 'fecha_reservacion', 'numero_reservacion', 'hora_reservacion', 'fecha_entrada', 'fecha_salida', 'tipo_habitacion__nombre', 'cuartos', 'adultos', 'ninos', 'segmento_mercado', 'agencia', 'nombre', 'apellido_paterno', 'apellido_materno', 'correo', 'telefono', 'ciudad', 'estado', 'pais', 'codigo_postal', 'deposito', 'fecha_deposito', 'moneda', 'tarifa', 'comentario', 'usuario_reserva', 'status'))
			return JsonResponse({'lista_reservas': consulta})
		else:
			consulta = list(Reserva.objects.filter(status='R').order_by('-id').values('id', 'fecha_reservacion', 'numero_reservacion', 'hora_reservacion', 'fecha_entrada', 'fecha_salida', 'tipo_habitacion__nombre', 'cuartos', 'adultos', 'ninos', 'segmento_mercado', 'agencia', 'nombre', 'apellido_paterno', 'apellido_materno', 'correo', 'telefono', 'ciudad', 'estado', 'pais', 'codigo_postal', 'deposito', 'fecha_deposito', 'moneda', 'tarifa', 'comentario', 'usuario_reserva', 'status'))
			return render(request, 'configuracion/configura_reserva.html', {'lista_reservas': consulta, 'hotel': hotel})


def numero_reserva(self):
	consulta = Reserva.objects.all().count()
	return JsonResponse({'data': consulta})


@login_required
def lee_segmento_agencia(request):
	consulta = list(TabHt.objects.all().values('id', 'segmento_web', 'agencia_web'))
	segmento_mercado = consulta[0]['segmento_web']
	agencia = consulta[0]['agencia_web']
	data = {
		"segmento": segmento_mercado,
		"agencia": agencia
	}
	return data


def guarda_reserva_cnts(request, status):
	if request.method == 'POST':
		form_DbDatos = DbDatosForm(request.POST)
		tipo_habitacion = list(Habitacion.objects.filter(id=request.POST.get('tipo_habitacion')).values('clave'))
		if form_DbDatos.is_valid():
			formulario = form_DbDatos.save(commit=False)
			formulario.nombreda = request.POST.get('apellido_paterno') + ' ' + request.POST.get('apellido_materno') + ' ' + request.POST.get('nombre')
			formulario.statusda = status
			formulario.ciudadda = request.POST.get('ciudad')
			formulario.cupon = request.POST.get('numero_reservacion')
			formulario.fhaentda = request.POST.get('fecha_entrada')
			formulario.fhasalda = request.POST.get('fecha_salida')
			formulario.observda = request.POST.get('comentario')
			formulario.paisda = request.POST.get('pais')
			formulario.deposida = request.POST.get('deposito')
			formulario.fhadepda = request.POST.get('fecha_deposito')
			formulario.numperda = request.POST.get('adultos')
			formulario.tpocam1da = request.POST.get('moneda')
			formulario.cveestda1 = tipo_habitacion[0]['clave']
			formulario.cveestda2 = request.POST.get('agencia')
			formulario.cveestda4 = request.POST.get('segmento_mercado')
			formulario.estadoda = request.POST.get('estado')
			formulario.tarifada = request.POST.get('tarifa')
			formulario.numcuada = request.POST.get('cuartos')
			formulario.fharesda = request.POST.get('fecha_reservacion')
			formulario.iniresda = request.POST.get('usuario_reserva')
			formulario.horaresda = request.POST.get('hora_reservacion')
			formulario.numninda = request.POST.get('ninos')
			formulario.nombr_da = request.POST.get('nombre')
			formulario.appat_da = request.POST.get('apellido_paterno')
			formulario.apmat_da = request.POST.get('apellido_materno')
			formulario.email_da = request.POST.get('correo')
			formulario.codposda = request.POST.get('codigo_postal')
			formulario.telefoda = request.POST.get('telefono')
			formulario.save()


def cancela_reserva_cnts(request):
	status = 'C'
	if request.method == 'GET':
		form_DbDatos = DbDatosForm(request.GET)
		reserva_id = request.GET.get('id')
		consulta = list(Reserva.objects.filter(id=reserva_id).values('fecha_reservacion', 'numero_reservacion', 'hora_reservacion', 'fecha_entrada', 'fecha_salida', 'tipo_habitacion', 'cuartos', 'adultos', 'ninos', 'segmento_mercado', 'agencia', 'nombre', 'apellido_paterno', 'apellido_materno', 'correo', 'telefono', 'ciudad', 'estado', 'pais', 'codigo_postal', 'deposito', 'fecha_deposito', 'moneda', 'tarifa', 'comentario', 'usuario_reserva', 'status'))
		formulario = form_DbDatos.save(commit=False)
		formulario.nombreda = consulta[0]['apellido_paterno'] + ' ' + consulta[0]['apellido_materno'] + ' ' + consulta[0]['nombre']
		formulario.statusda = status
		formulario.ciudadda = consulta[0]['ciudad']
		formulario.cupon = consulta[0]['numero_reservacion']
		formulario.fhaentda = consulta[0]['fecha_entrada']
		formulario.fhasalda = consulta[0]['fecha_salida']
		formulario.observda = consulta[0]['comentario']
		formulario.paisda = consulta[0]['pais']
		formulario.deposida = consulta[0]['deposito']
		formulario.fhadepda = consulta[0]['fecha_deposito']
		formulario.numperda = consulta[0]['adultos']
		formulario.tpocam1da = consulta[0]['moneda']
		formulario.cveestda1 = consulta[0]['tipo_habitacion']
		formulario.cveestda2 = consulta[0]['agencia']
		formulario.cveestda4 = consulta[0]['segmento_mercado']
		formulario.estadoda = consulta[0]['estado']
		formulario.tarifada = consulta[0]['tarifa']
		formulario.numcuada = consulta[0]['cuartos']
		formulario.fharesda = consulta[0]['fecha_reservacion']
		formulario.iniresda = consulta[0]['usuario_reserva']
		formulario.horaresda = consulta[0]['hora_reservacion']
		formulario.numninda = consulta[0]['ninos']
		formulario.nombr_da = consulta[0]['nombre']
		formulario.appat_da = consulta[0]['apellido_paterno']
		formulario.apmat_da = consulta[0]['apellido_materno']
		formulario.email_da = consulta[0]['correo']
		formulario.codposda = consulta[0]['codigo_postal']
		formulario.telefoda = consulta[0]['telefono']
		print(consulta[0]['tipo_habitacion'])
		formulario.save()


@login_required
def agrega_reserva_view(request):
	status = request.POST.get('status')
	if request.method == 'POST':
		form_Reserva = ReservaForm(request.POST)
		if form_Reserva.is_valid():
			form_Reserva.save()
			guarda_reserva_cnts(request, status)
			return redirect('reserva')
	else:
		form_Reserva = ReservaForm()
	return render(request, 'configuracion/agrega_reserva.html', {'form': form_Reserva, 'datos': lee_segmento_agencia(request)})


@login_required
def cancela_reserva_view(request):
	if request.method == 'GET':
		valor = request.GET.get('id')
		Reserva.objects.filter(id=valor).update(status='C')
		cancela_reserva_cnts(request)
	return JsonResponse({'data': 'ok'})


@login_required
def edita_reserva_view(request, id):
	status = 'M'
	guarda_reserva_cnts(request, status)
	reserva = Reserva.objects.get(id=id)
	if request.method == 'POST':
		form = ReservaForm(request.POST, instance=reserva)
		if form.is_valid():
			form.save()
			return redirect('reserva')
	else:
		form = ReservaForm(instance=reserva)
	return render(request, 'configuracion/edita_reserva.html', {'form': form})

# MOTOR DE RESERVACIONES: Inicia reserva
def busca_disponibilidad_view(request):
	return render(request, 'reserva/disponibilidad.html', {'datos': trae_datos()})


def reserva_motor(request):
	status = request.POST.get('status')
	if request.method == 'POST':
		form_Reserva = ReservaForm(request.POST)
		if form_Reserva.is_valid():
			form_Reserva.save()
			#guarda_reserva_cnts(request, status)
			#return redirect('reserva')
	else:
		form_Reserva = ReservaForm()
	return render(request, 'reserva/reservar.html', {'form': form_Reserva, 'datos': trae_datos()})


def confirma_motor(request):
	return render(request, 'reserva/confirmar.html', {'datos': trae_datos()})

templates/reserva/confirmar.html
{% extends 'base_motor.html' %}

{% load static %}

{% block titulo %}Habitaciones{% endblock %}

{% block contenido %}
	{% for item in datos %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <div class="container-fluid logo_menu">
		    <a class="navbar-brand" href="#">
		    	<img src="/media/{{ item.edificio_logo }}" alt="" class="d-inline-block align-text-top logo">
		    </a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarText">
		      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
			        <li class="nav-item">
			        	<a class="nav-link active" aria-current="page" href="{{ item.motor_direccion_menu }}" target="_blank">{{ item.motor_opcion_menu }}</a>
			        </li>
		      </ul>
		    </div>
		  </div>
		</nav>

		<section class="banner">
				<img src="/media/{{ item.edificio_banner }}" alt="banner">
			<div class="textos">
				<h2>{{ item.edificio_nombre }}</h2>
				<h6>{{ item.edificio_direccion }}</h6>
			</div>
			<div class="cuadro_negro"></div>
		</section>

		<section>
			<div class="container">
				<div class="row">
					<div class="col-xs-9 sin-fondo">
						<!--- Inicia Porceso de Reserva Web -->
						<div class="etapas">
							<div class="tarjeta-personalizada">
								<span class="numero">1</span><label class="etiqueta">Habitaciones y Tarifas</label>
							</div>

							<div class="tarjeta-personalizada">
								<span class="numero">2</span><label class="etiqueta">Información</label>
							</div>

							<div class="tarjeta-personalizada-activa">
								<span class="numero">3</span><label class="etiqueta">Confirmación</label>
							</div>
						</div>

						<h3>Datos</h3>

					</div>

					<div class="col-xs-3">
						<div method="POST" class="contenedor_formulario">
							{% csrf_token %}

							<div class="titulo_div">
								Mi reserva
							</div>

							<a href="#" class="btn btn-success btn-busca-hab">Buscar <i class="fas fa-search"></i></a>
							<!--<button type="submit" class="btn btn-sm btn-success btn-busca-hab">Guardar <i class="fas fa-search"></i></button>-->
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endfor %}
{% endblock %}

<!-- CORREGIR ESTE FOOTER -->
{% block footer %}
	{% for item in consulta %}
		{{ item.edificio_telefono }}
	{% endfor %}
{% endblock %}

{% block jsPersonal %}
	<script src="{% static 'js/all.min.js' %}"></script>
{% endblock %}

templates/reserva/disponibilidad.html
{% extends 'base_motor.html' %}

{% load static %}

{% block titulo %}Habitaciones{% endblock %}

{% block contenido %}
	{% for item in datos %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <div class="container-fluid logo_menu">
		    <a class="navbar-brand" href="#">
		    	<img src="/media/{{ item.edificio_logo }}" alt="" class="d-inline-block align-text-top logo">
		    </a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarText">
		      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
			        <li class="nav-item">
			        	<a class="nav-link active" aria-current="page" href="{{ item.motor_direccion_menu }}" target="_blank">{{ item.motor_opcion_menu }}</a>
			        </li>
		      </ul>
		    </div>
		  </div>
		</nav>

		<section class="banner">
				<img src="/media/{{ item.edificio_banner }}" alt="banner">
			<div class="textos">
				<h2>{{ item.edificio_nombre }}</h2>
				<h6>{{ item.edificio_direccion }}</h6>
			</div>
			<div class="cuadro_negro"></div>
		</section>

		<section>
			<div class="container">
				<div class="row">
					<div class="col-xs-9 sin-fondo">
						<!--- Inicia Porceso de Reserva Web -->
						<div class="etapas">
							<div class="tarjeta-personalizada-activa">
								<span class="numero">1</span><label class="etiqueta">Habitaciones y Tarifas</label>
							</div>

							<div class="tarjeta-personalizada">
								<span class="numero">2</span><label class="etiqueta">Información</label>
							</div>

							<div class="tarjeta-personalizada">
								<span class="numero">3</span><label class="etiqueta">Confirmación</label>
							</div>
						</div>

						<div class="filtro">
							<div class="tarjeta">
								<label class="etiqueta2">Habitaciones disponibles <span class="badge bg-success">2</span></label>

								<label class="etiqueta-filtro">
									Ordenar por:
								</label>
								<select name="agrupar" class="form-select filtro_habitaciones" id="agrupar">
									<option>Habitaciones</option>
									<option>Tarifas</option>
								</select>
							</div>
						</div>

						<div class="resultado">
							<div class="card mb-3 tarjeta-habitacion" style="max-width: 540px;">
							  <div class="row g-0">
							    <div class="col-md-4">
							      <img src="{% static 'img/Pcaribe.jpg' %}" class="img-fluid rounded-start" alt="caribe">
							    </div>
							    <div class="col-md-8">
							      <div class="card-body">
							        <h5 class="card-title">Nombre Habitación</h5>
							        <p class="card-text">Amenidades</p>
							        <p class="card-text"><small class="text-muted"><a href="#">Ver galería</a></small></p>
							      </div>
							    </div>
							  </div>
							</div>

							<div class="precio">
								<label class="desde"><small>Desde</small></label>
								<div class="text-primary monto">
									$ 800.00
								</div>
								<label class="noches"><small>por habitación por noche</small></label>
<!--
								<button class="btn btn-success btn-reservar">Reservar <i class="fas fa-bell"></i></button>
-->
								<a href="{% url 'reservar' %}" class="btn btn-sm btn-success btn-busca-hab">Reservar <i class="fas fa-bell"></i></a>
							</div>
						</div>
					</div>

					<div class="col-xs-3">
						<form method="POST" class="contenedor_formulario">
							{% csrf_token %}

							<div class="titulo_div">
								Buscar disponibilidad
							</div>

							<div class="input-group">
								<label>Llegada</label>
								<input type="date" name="fecha_entrada" id="id_fecha_entrada" class="form-control">
							</div>

							<div class="input-group">
								<label>Salida</label>
								<input type="date" name="fecha_salida" id="id_fecha_salida" class="form-control">
							</div>

							<div class="input-group">
								<label class="adultos">Adultos</label>
								<select class="form-select" name="adultos" id="id_adultos">
								  <option value="1" selected>1</option>
								  <option value="2">2</option>
								  <option value="3">3</option>
								  <option value="4">4</option>
								</select>
							</div>

							<div class="input-group">
								<label class="ninos">Niños <small>(Edades 0-10)</small></label>
								<select class="form-select" name="ninos" id="id_ninos">
								  <option value="0" selected>0</option>
								  <option value="1">1</option>
								  <option value="2">2</option>
								  <option value="3">3</option>
								</select>
							</div>

							<a href="#" class="btn btn-sm btn-success btn-busca-hab">Buscar <i class="fas fa-search"></i></a>
							<!--<button type="submit" class="btn btn-sm btn-success btn-busca-hab">Guardar <i class="fas fa-search"></i></button>-->
						</form>
					</div>
				</div>
			</div>
		</section>
	{% endfor %}
{% endblock %}

<!-- CORREGIR ESTE FOOTER -->
{% block footer %}
	{% for item in consulta %}
		{{ item.edificio_telefono }}
	{% endfor %}
{% endblock %}

{% block jsPersonal %}
	<script src="{% static 'js/all.min.js' %}"></script>
{% endblock %}

templates/reserva/reservar.html
{% extends 'base_motor.html' %}

{% load static %}

{% block titulo %}Habitaciones{% endblock %}

{% block contenido %}
	{% for item in datos %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <div class="container-fluid logo_menu">
		    <a class="navbar-brand" href="#">
		    	<img src="/media/{{ item.edificio_logo }}" alt="" class="d-inline-block align-text-top logo">
		    </a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarText">
		      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
			        <li class="nav-item">
			        	<a class="nav-link active" aria-current="page" href="{{ item.motor_direccion_menu }}" target="_blank">{{ item.motor_opcion_menu }}</a>
			        </li>
		      </ul>
		    </div>
		  </div>
		</nav>

		<section class="banner">
				<img src="/media/{{ item.edificio_banner }}" alt="banner">
			<div class="textos">
				<h2>{{ item.edificio_nombre }}</h2>
				<h6>{{ item.edificio_direccion }}</h6>
			</div>
			<div class="cuadro_negro"></div>
		</section>

		<section>
			<div class="container">
				<div class="row">
					<div class="col-xs-9 sin-fondo">
						<!--- Inicia Porceso de Reserva Web -->
						<div class="etapas">
							<div class="tarjeta-personalizada">
								<span class="numero">1</span><label class="etiqueta">Habitaciones y Tarifas</label>
							</div>

							<div class="tarjeta-personalizada-activa">
								<span class="numero">2</span><label class="etiqueta">Información</label>
							</div>

							<div class="tarjeta-personalizada">
								<span class="numero">3</span><label class="etiqueta">Confirmación</label>
							</div>
						</div>

						<h3>Datos Personales</h3>

						<form method="POST">
							{% csrf_token %}

							{{ form.as_p }}

							<a href="{% url 'confirmar' %}" class="btn btn-sm btn-success btn-busca-hab">Reservar <i class="fas fa-bell"></i></a>
						</form>
					</div>

					<div class="col-xs-3">
						<div method="POST" class="contenedor_formulario">
							{% csrf_token %}

							<div class="titulo_div">
								Mi reserva
							</div>

							<a href="#" class="btn btn-success btn-busca-hab">Buscar <i class="fas fa-search"></i></a>
							<!--<button type="submit" class="btn btn-sm btn-success btn-busca-hab">Guardar <i class="fas fa-search"></i></button>-->
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endfor %}
{% endblock %}

<!-- CORREGIR ESTE FOOTER -->
{% block footer %}
	{% for item in consulta %}
		{{ item.edificio_telefono }}
	{% endfor %}
{% endblock %}

{% block jsPersonal %}
	<script src="{% static 'js/all.min.js' %}"></script>
{% endblock %}