apps/configuracion/urls.py
from django.urls import path


urlpatterns = [
]

motorreserva/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


handler404 = 'apps.configuracion.views.error_404'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.login.urls')),

    path('dashboard/', include('apps.dashboard.urls')),
    path('configura/', include('apps.configuracion.urls')),
    path('edificio/', include('apps.edificio.urls')),
    path('habitacion/', include('apps.habitacion.urls')),
    path('tarifa/', include('apps.tarifa.urls')),
    path('reserva/', include('apps.reserva.urls')),
    path('sitio/', include('apps.sitio.urls')),
    path('motor/', include('apps.motor.urls')),
    path('perfil/', include('apps.perfil.urls')),
    path('reporte/', include('apps.reporte.urls')),
    path('digital/', include('apps.digital.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/configuracion/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class DbCapct(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    cgrupo = models.IntegerField(db_column='CGRUPO', blank=True, null=True)  # Field name made lowercase.
    cnumero = models.IntegerField(db_column='CNUMERO', blank=True, null=True)  # Field name made lowercase.
    creser = models.IntegerField(db_column='CRESER', blank=True, null=True)  # Field name made lowercase.
    ccuarto = models.SmallIntegerField(db_column='CCUARTO', blank=True, null=True)  # Field name made lowercase.
    ccuenta = models.IntegerField(db_column='CCUENTA', blank=True, null=True)  # Field name made lowercase.
    ccargo = models.DecimalField(db_column='CCARGO', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    ccredito = models.DecimalField(db_column='CCREDITO', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    cstatus = models.IntegerField(db_column='CSTATUS', blank=True, null=True)  # Field name made lowercase.
    cfecha = models.DateField(db_column='CFECHA', blank=True, null=True)  # Field name made lowercase.
    crefer = models.CharField(db_column='CREFER', max_length=120, blank=True, null=True)  # Field name made lowercase.
    cpase = models.CharField(db_column='CPASE', max_length=4, blank=True, null=True)  # Field name made lowercase.
    cage = models.CharField(db_column='CAGE', max_length=3, blank=True, null=True)  # Field name made lowercase.
    cfactura = models.IntegerField(db_column='CFACTURA', blank=True, null=True)  # Field name made lowercase.
    cnumhues = models.IntegerField(db_column='CNUMHUES', blank=True, null=True)  # Field name made lowercase.
    chora = models.CharField(db_column='CHORA', max_length=8, blank=True, null=True)  # Field name made lowercase.
    crefnum = models.IntegerField(db_column='CREFNUM', blank=True, null=True)  # Field name made lowercase.
    chabt = models.SmallIntegerField(db_column='CHABT', blank=True, null=True)  # Field name made lowercase.
    chuest = models.IntegerField(db_column='CHUEST', blank=True, null=True)  # Field name made lowercase.
    cpaqte = models.CharField(db_column='CPAQTE', max_length=6, blank=True, null=True)  # Field name made lowercase.
    cfolpaq = models.IntegerField(db_column='CFOLPAQ', blank=True, null=True)  # Field name made lowercase.
    ctipmov = models.CharField(db_column='CTIPMOV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    folio_pago = models.IntegerField(db_column='FOLIO_PAGO', blank=True, null=True)  # Field name made lowercase.
    estatus = models.CharField(db_column='ESTATUS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    cxc = models.CharField(db_column='CXC', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ctadep = models.IntegerField(db_column='CTADEP', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'DB_CAPCT'


class DbDatos(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nombreda = models.CharField(db_column='NOMBREDA', max_length=100, blank=True, null=True)  # Field name made lowercase.
    statusda = models.CharField(db_column='STATUSDA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    ciudadda = models.CharField(db_column='CIUDADDA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    numresda = models.IntegerField(db_column='NUMRESDA', blank=True, null=True)  # Field name made lowercase.
    fhaentda = models.DateField(db_column='FHAENTDA', blank=True, null=True)  # Field name made lowercase.
    fhasalda = models.DateField(db_column='FHASALDA', blank=True, null=True)  # Field name made lowercase.
    fhaextda = models.DateField(db_column='FHAEXTDA', blank=True, null=True)  # Field name made lowercase.
    numhabda = models.IntegerField(db_column='NUMHABDA', blank=True, null=True)  # Field name made lowercase.
    planvida = models.CharField(db_column='PLANVIDA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    observda = models.CharField(db_column='OBSERVDA', max_length=100, blank=True, null=True)  # Field name made lowercase.
    observda2 = models.CharField(db_column='OBSERVDA2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    dirda = models.CharField(db_column='DIRDA', max_length=100, blank=True, null=True)  # Field name made lowercase.
    telda = models.CharField(db_column='TELDA', max_length=100, blank=True, null=True)  # Field name made lowercase.
    paisda = models.CharField(db_column='PAISDA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    formpada = models.CharField(db_column='FORMPADA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    deposida = models.DecimalField(db_column='DEPOSIDA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    fhadepda = models.DateField(db_column='FHADEPDA', blank=True, null=True)  # Field name made lowercase.
    numperda = models.SmallIntegerField(db_column='NUMPERDA', blank=True, null=True)  # Field name made lowercase.
    tarifada = models.DecimalField(db_column='TARIFADA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    numcuada = models.SmallIntegerField(db_column='NUMCUADA', blank=True, null=True)  # Field name made lowercase.
    fechresda = models.DateField(db_column='FECHRESDA', blank=True, null=True)  # Field name made lowercase.
    cargo1da = models.DecimalField(db_column='CARGO1DA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    nomcar1da = models.CharField(db_column='NOMCAR1DA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cuencar1da = models.IntegerField(db_column='CUENCAR1DA', blank=True, null=True)  # Field name made lowercase.
    cargo2da = models.DecimalField(db_column='CARGO2DA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    nomcar2da = models.CharField(db_column='NOMCAR2DA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cuencar2da = models.IntegerField(db_column='CUENCAR2DA', blank=True, null=True)  # Field name made lowercase.
    cargo3da = models.DecimalField(db_column='CARGO3DA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    nomcar3da = models.CharField(db_column='NOMCAR3DA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cuencar3da = models.IntegerField(db_column='CUENCAR3DA', blank=True, null=True)  # Field name made lowercase.
    cargo4da = models.DecimalField(db_column='CARGO4DA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    nomcar4da = models.CharField(db_column='NOMCAR4DA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cuencar4da = models.IntegerField(db_column='CUENCAR4DA', blank=True, null=True)  # Field name made lowercase.
    cargo5da = models.DecimalField(db_column='CARGO5DA', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    nomcar5da = models.CharField(db_column='NOMCAR5DA', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cuencar5da = models.IntegerField(db_column='CUENCAR5DA', blank=True, null=True)  # Field name made lowercase.
    paseda = models.CharField(db_column='PASEDA', max_length=4, blank=True, null=True)  # Field name made lowercase.
    cupagda = models.CharField(db_column='CUPAGDA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    facturada = models.IntegerField(db_column='FACTURADA', blank=True, null=True)  # Field name made lowercase.
    fharesda = models.DateField(db_column='FHARESDA', blank=True, null=True)  # Field name made lowercase.
    nomfol1da = models.CharField(db_column='NOMFOL1DA', max_length=30, blank=True, null=True)  # Field name made lowercase.
    nomfol2da = models.CharField(db_column='NOMFOL2DA', max_length=30, blank=True, null=True)  # Field name made lowercase.
    nomfol3da = models.CharField(db_column='NOMFOL3DA', max_length=30, blank=True, null=True)  # Field name made lowercase.
    folex1da = models.CharField(db_column='FOLEX1DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    folex2da = models.CharField(db_column='FOLEX2DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    folex3da = models.CharField(db_column='FOLEX3DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    folex4da = models.CharField(db_column='FOLEX4DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    folex5da = models.CharField(db_column='FOLEX5DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    folex6da = models.CharField(db_column='FOLEX6DA', max_length=3, blank=True, null=True)  # Field name made lowercase.
    auditda = models.CharField(db_column='AUDITDA', max_length=1, blank=True, null=True)  # Field name made lowercase.
    horasalida = models.CharField(db_column='HORASALIDA', max_length=5, blank=True, null=True)  # Field name made lowercase.
    horaentrad = models.CharField(db_column='HORAENTRAD', max_length=5, blank=True, null=True)  # Field name made lowercase.

apps/sitio/models.py
from django.db import models


# DATOS DE CONFIGURACIÓN DE CNTS WEB
class Sitio(models.Model):
	IDIOMAS_DISPONIBLES = (
		('', ''),
        ('ESP', 'Español'),
        ('ING', 'Inglés'),
    )
	nombre_configuracion = models.CharField(max_length=50, default='default', unique=True)
	# COLORES
	logo = models.ImageField(upload_to='sitio/', blank=True, null=True)
	color_fondo = models.CharField(max_length=7, default='#f5f7fb')
	color_fondo_sidebar = models.CharField(max_length=7, default='#0078d4')
	color_fondo_navbar = models.CharField(max_length=7, default='#ffffff')
	color_fondo_footer = models.CharField(max_length=7, default='#ffffff')
	# IDIOMAS
	idioma = models.CharField(max_length=3, choices=IDIOMAS_DISPONIBLES, default='ESP')
	status = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'Configuración'
		verbose_name_plural = 'Configuraciones'

	def __str__(self):
		return self.nombre_configuracion

apps/configuracion/forms.py
from django import forms
from .models import TabEst, DbDatos


class TabEstForm(forms.ModelForm):
	class Meta:
		model = TabEst
		fields = '__all__'
		widgets = {
			'clave': forms.TextInput(attrs={'class': 'form-control'}),
			'descrip': forms.TextInput(attrs={'class': 'form-control'}),
			'otro1': forms.TextInput(attrs={'class': 'form-control'}),
			'otro2': forms.TextInput(attrs={'class': 'form-control'}),
			'otro3': forms.TextInput(attrs={'class': 'form-control'}),
		}


class DbDatosForm(forms.ModelForm):
	class Meta:
		model = DbDatos
		fields = '__all__'
		widgets = {
			'nombreda': forms.TextInput(attrs={'class': 'form-control', 'hidden': 'hidden'}),
			'statusda': forms.TextInput(attrs={'class': 'form-control', 'value': 'R', 'hidden': 'hidden'}),
			'ciudadda': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'Ciudad'}),
			'fhaentda': forms.TextInput(attrs={'class': 'form-control fecha', 'type': 'date'}),
			'fhasalda': forms.TextInput(attrs={'class': 'form-control fecha', 'type': 'date'}),
			'paisda': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'País'}),
			'deposida': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'value': '0.00'}),
			'fhadepda': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
			'numperda': forms.NumberInput(attrs={'class': 'form-control', 'value': '1'}),
			'tpocam1da': forms.Select(attrs={'class': 'form-select'}),
			'cveestda1': forms.Select(attrs={'class': 'form-select'}),
			'estadoda': forms.TextInput(attrs={'class': 'form-control treinta', 'placeholder': 'Estado'}),
			'tarifada': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'value': '0.00'}),
			'numcuada': forms.NumberInput(attrs={'class': 'form-control cincuenta', 'value': '1'}),
			'fharesda': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'hidden': 'hidden'}),
			'iniresda': forms.TextInput(attrs={'class': 'form-control', 'value': 'WEB', 'hidden': 'hidden'}),
			'infantes': forms.NumberInput(attrs={'class': 'form-control', 'value': '0'}),
			'nombr_da': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Nombre'}),
			'appat_da': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Apellido Paterno'}),
			'apmat_da': forms.TextInput(attrs={'class': 'form-control nombapell', 'placeholder': 'Apellido Materno'}),
			'email_da': forms.TextInput(attrs={'class': 'form-control'}),
			'telefoda': forms.TextInput(attrs={'class': 'form-control'}),
		}

apps/configuracion/views.py
#import asyncio
#import MySQLdb as sql
#
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpRequest
#from .models import ConfiguracionSitio
#from .forms import ConfiguracionSitioForm


def error_404(request, exception):
	return render(request, '404.html')
"""
# Falta funcion para cargar los datos de configuracion en los templates
@login_required
def sitio_view(request):
	consulta = list(ConfiguracionSitio.objects.all().values())
	return render(request, 'configuracion/configura_sitio.html', {'consulta': consulta})


def edita_configuracion_sitio_view(request):
	try:
		datos = HttpRequest.read(request)
		datos_decodificados = datos.decode('utf-8')
		datos_separados = datos_decodificados.split(',')
		#nombre_configuracion_form = datos['nombre_configuracion']
		print(datos_separados[0].strip())
		#consulta_configuracion = ConfiguracionSitio.objects.filter(nombre_configuracion=nombre_configuracion_form).values()
		#return JsonResponse({'respuesta': list(consulta_configuracion)}, safe=False)
	except Exception as e:
		print(e)

	if request.method == 'POST':
		form = ConfiguracionSitioForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('sitio')
	else:
		form = ConfiguracionSitioForm()
	return render(request, 'configuracion/edita_sitio.html', {'form': form})


@login_required
def borra_registro_view(request, id):
	# Falta agregar la inserción a la BD
	DbDatos.objects.filter(id=id).update(statusda='C')
	return redirect('reserva')
"""

templates/configuracion/agrega_edificio.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}Configuración{% endblock %}

{% block menu_lateral %}
	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'dashboard' %}">
			<i class="fas fa-chart-bar"></i> <span class="align-middle">Dashboard</span>
		</a>
	</li>

	<li class="sidebar-header">
		Configuración
	</li>

	<li class="sidebar-item active">
		<a class="sidebar-link" href="{% url 'edificio' %}">
			<i class="fas fa-hotel"></i> <span class="align-middle">Propiedad</span>
		</a>
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'habitacion' %}">
			<i class="fas fa-door-closed"></i> <span class="align-middle">Habitación</span>
		</a>
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="pages-sign-up.html">
			<i class="fas fa-dollar-sign"></i> <span class="align-middle">Tarifa</span>
		</a>
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'sitio' %}">
			<i class="fas fa-sliders-h"></i> <span class="align-middle">Sitio Web</span>
		</a>
	</li>

	<li class="sidebar-header">
		Motor de Reservaciones
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'motor' %}">
			<i class="fas fa-cog"></i> <span class="align-middle">Motor</span>
		</a>
	</li>

	<li class="sidebar-header">
		Reservaciones
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'reserva' %}">
			<i class="fas fa-calendar-check"></i> <span class="align-middle">Reserva</span>
		</a>
	</li>

	<li class="sidebar-header">
		Reportes
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'rack' %}">
			<i class="fas fa-border-all"></i> <span class="align-middle">Rack</span>
		</a>
	</li>
{% endblock %}

{% block titulo_seccion_a %}Configuración{% endblock %}

{% block contenido %}
	<div class="row">
		<div class="col-12 col-lg-12 col-xxl-12 d-flex">
			<div class="card flex-fill">
				<div class="card-header">
					<h5 class="card-title mb-0 regresar">
						Habitación <span class="lnk-regresar"><a href="{% url 'edificio' %}"><i class="fas fa-chevron-left"></i> Regresar</a></span>
					</h5>
				</div>

				<form class="formulario" method="POST" enctype="multipart/form-data">
					{% csrf_token %}

					<div class="izquierda">
						<label class="form-label">Nombre</label>
						{{ form.nombre }}

						<label class="form-label">Nombre Corto</label>
						{{ form.nombre_corto }}

						<label class="form-label">Dirección</label>
						{{ form.direccion }}

						<label class="form-label">Correo</label>
						{{ form.correo }}

						<label class="form-label">Telefono</label>
						{{ form.telefono }}

						<label class="form-label">Paǵina Web</label>
						{{ form.web }}

						<label class="form-label">Facebook</label>
						{{ form.facebook }}
					</div>
					<div class="derecha">
						<label class="form-label">Twitter</label>
						{{ form.twitter }}

						<label class="form-label">Instagram</label>
						{{ form.instagram }}

						<label class="form-label">Foto del Hotel</label>
						{{ form.foto }}

						<label class="form-label">Logo del Hotel</label>
						{{ form.logo }}

						<label class="form-label">Banner</label>
						{{ form.banner }}

						<label class="form-label">Fondo de la Página de Reservas Directas</label>
						{{ form.background_reserva_directa }}
					</div>

					<button class="btn btn-success btn-guarda-hab">Guardar <i class="fas fa-save"></i></button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/configuracion/agrega_sitio.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}Configuración{% endblock %}

{% block menu_lateral %}
	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'dashboard' %}">
			<i class="fas fa-chart-bar"></i> <span class="align-middle">Dashboard</span>
		</a>
	</li>

	<li class="sidebar-header">
		Configuración
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'edificio' %}">
			<i class="fas fa-hotel"></i> <span class="align-middle">Propiedad</span>
		</a>
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="#">
			<i class="fas fa-door-closed"></i> <span class="align-middle">Habitación</span>
		</a>
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="pages-sign-up.html">
			<i class="fas fa-dollar-sign"></i> <span class="align-middle">Tarifa</span>
		</a>
	</li>

	<li class="sidebar-item active">
		<a class="sidebar-link" href="{% url 'sitio' %}">
			<i class="fas fa-sliders-h"></i> <span class="align-middle">Sitio Web</span>
		</a>
	</li>

	<li class="sidebar-header">
		Motor de Reservaciones
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'motor' %}">
			<i class="fas fa-cog"></i> <span class="align-middle">Motor</span>
		</a>
	</li>

	<li class="sidebar-header">
		Reservaciones
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'reserva' %}">
			<i class="fas fa-calendar-check"></i> <span class="align-middle">Reserva</span>
		</a>
	</li>

	<li class="sidebar-header">
		Reportes
	</li>

	<li class="sidebar-item">
		<a class="sidebar-link" href="{% url 'rack' %}">
			<i class="fas fa-border-all"></i> <span class="align-middle">Rack</span>
		</a>
	</li>
{% endblock %}

{% block titulo_seccion_a %}Configuración{% endblock %}

{% block contenido %}
	<div class="row">
		<div class="col-12 col-lg-12 col-xxl-12 d-flex">
			<div class="card flex-fill">
				<div class="card-header">
					<h5 class="card-title mb-0 regresar">
						Colores e Idioma <span class="lnk-regresar"><a href="{% url 'sitio' %}"><i class="fas fa-chevron-left"></i> Regresar</a></span>
					</h5>
				</div>

				<form class="formulario" method="POST">
					{% csrf_token %}

					<div class="izquierda">
						<label class="form-label">Nombre para la configuracion</label>
						<input type="text" name="nombre_configuracion" class="form-control" required="required" id="id_nombre_configuracion">

						<label class="form-label">Color de Fondo del Área de Trabajo</label>
						<input type="color" name="color_fondo" class="form-control" id="id_color_fondo">

						<label class="form-label">Color de Fondo del Menú Lateral</label>
						<input type="color" name="color_fondo_sidebar" class="form-control" id="id_color_fondo_sidebar">
					</div>
					<div class="derecha">
						<label class="form-label">Color de Fondo de la Barra de Navegación</label>
						<input type="color" name="color_fondo_navbar" class="form-control" id="id_color_fondo_navbar">

						<label class="form-label">Color de Fondo del Pie de Página</label>
						<input type="color" name="color_fondo_footer" class="form-control" id="id_color_fondo_footer">

						<label class="form-label">Idioma del Sitio</label>
						<select name="idioma" class="form-select" required="" id="id_idioma">
							<option value=""  selected="selected"></option>
						  	<option value="ESP">Español</option>
						  	<option value="ING">Inglés</option>
						</select>
					</div>

					<button class="btn btn-success btn-guarda-conf">Guardar <i class="fas fa-save"></i></button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block scriptJS %}
	<script src="{% static 'js/sitio.js' %}"></script>
{% endblock %}